export const PORTFOLIO_STATS = [
  {
    title: 'Net Asset Value',
    value: '620,000',
    isPercentage: false,
    hasPositiveIcon: false,
    hasNegativeIcon: false,
  },
  {
    title: 'Starting NAV',
    value: '250,000',
    isPercentage: false,
    hasPositiveIcon: false,
    hasNegativeIcon: false,
  },
  {
    title: 'Cash',
    value: '121,281',
    isPercentage: false,
    hasPositiveIcon: true,
    hasNegativeIcon: false,
  },
  {
    title: 'YTD Return',
    value: '-13.48',
    isPercentage: true,
    hasPositiveIcon: false,
    hasNegativeIcon: true,
  },
  {
    title: 'Benchmark Level',
    value: '5,970.00',
    isPercentage: false,
    hasPositiveIcon: false,
    hasNegativeIcon: false,
  },
  {
    title: 'Yield',
    value: '27.80',
    isPercentage: true,
    hasPositiveIcon: false,
    hasNegativeIcon: false,
  },
  {
    title: 'Sharpe Ratio',
    value: '1.60',
    isPercentage: false,
    hasPositiveIcon: false,
    hasNegativeIcon: false,
  },
  {
    title: 'Beta',
    value: '0.81',
    isPercentage: false,
    hasPositiveIcon: false,
    hasNegativeIcon: false,
  },
  {
    title: 'Volatility',
    value: '42',
    isPercentage: false,
    hasPositiveIcon: false,
    hasNegativeIcon: false,
  },
]
